backend:
  name: git-gateway
  branch: master
local_backend: true
collections:
  - name: pages
    label: Pages
    files:
      - name: about
        label: About
        file: src/routes/about/+page.md
        fields:
          - name: title
            label: Titre
          - name: cover
            label: Image
            widget: image
          - name: body
            label: Texte
            widget: markdown
      - name: animations
        label: Animations
        file: src/routes/animations/+page.md
        fields:
          - name: animations
            label: Animations
            widget: list
            fields:
              - name: url
                label: Lien
              - name: title
                label: Titre
              - name: caption
                label: Légende
                required: false
                widget: markdown
      - name: archives
        label: Archives
        file: src/routes/archives/+page.md
        fields:
          - name: gallery
            label: Galerie
            widget: list
            fields:
              - name: image
                label: Image
                widget: image
              - name: caption
                label: Légende
                widget: markdown
      - name: misc
        label: En vrac
        file: src/routes/en-vrac/+page.md
        fields:
          - name: gallery
            label: Galerie
            widget: list
            fields:
              - name: image
                label: Image
                widget: image
              - name: caption
                label: Légende
                widget: markdown
      - name: events
        label: Événements
        file: src/routes/evenements/+page.md
        fields:
          - name: events
            label: Événements
            label_singular: Événement
            widget: list
            fields:
              - name: date
                label: Date
                widget: datetime
                time_format: false
              - name: title
                label: Titre
              - name: description
                label: Description
                widget: markdown
              - name: video
                label: Vidéo
                required: false
              - name: images
                label: Images
                label_singular: Image
                widget: list
                field: { name: image, label: image, widget: image }
                required: false
  - name: objects
    label: Objets
    label_singular: Objet
    folder: src/routes/objets
    slug: '{{slug}}/+page'
    path: '{{slug}}/+page.md'
    create: true
    fields:
      - name: title
        label: Titre
      - name: cover
        label: Image
        widget: image
      - name: description
        label: Description
        widget: markdown
      - name: models
        label: Modèles
        widget: list
        fields:
          - name: title
            label: Titre
          - name: cover
            label: Image
            widget: image
          - name: description
            label: Description
            widget: markdown
locale: 'fr'
media_folder: 'static/uploads'
public_folder: '/uploads'
site_url: https://claire-olives-design.netlify.app
display_url: https://claire-olives-design.netlify.app
logo_url: https://claire-olives-design.netlify.app/uploads/logo.png