backend:
  name: git-gateway
  branch: master
local_backend: true
locale: fr
media_folder: static/uploads
public_folder: /uploads
site_url: https://claire-olives-design.netlify.app
display_url: https://claire-olives-design.netlify.app
logo_url: https://claire-olives-design.netlify.app/uploads/logo.png
collections:
  - name: pages
    label: Pages
    files:
      - name: about
        label: About
        file: src/routes/about/+page.md
        fields:
          - name: title
            label: Titre
          - name: image
            label: Image
            widget: image
          - name: caption
            label: Légende
            required: false
          - name: body
            label: Texte
            widget: markdown
      - name: animations
        label: Animations
        file: src/routes/animations/+page.md
        fields:
          - name: animations
            label: Animations
            widget: list
            fields:
              - name: url
                label: Lien
              - name: title
                label: Titre
              - name: caption
                label: Légende
                required: false
                widget: markdown
      - name: archives
        label: Archives
        file: src/routes/archives/+page.md
        fields:
          - name: archives
            label: Archives
            label_singular: Archive
            widget: list
            fields:
              - name: image
                label: Image
                widget: image
              - name: caption
                label: Légende
                widget: markdown
      - name: misc
        label: Vrac
        file: src/routes/vrac/+page.md
        fields:
          - name: gallery
            label: Images
            label_singular: Image
            widget: list
            fields:
              - name: image
                label: Image
                widget: image
              - name: caption
                label: Légende
                widget: markdown
      - name: exhibitions
        label: Expositions
        file: src/routes/expositions/+page.md
        fields:
          - name: exhibitions
            label: Expositions
            label_singular: Exposition
            widget: list
            fields:
              - name: date
                label: Date
                widget: datetime
                time_format: false
              - name: title
                label: Titre
              - name: description
                label: Description
                widget: markdown
              - name: video
                label: Vidéo
                required: false
              - name: images
                label: Images
                label_singular: Image
                widget: list
                field: { name: image, label: image, widget: image }
                required: false
  - name: objects
    label: Objets
    label_singular: Objet
    folder: src/routes/objets
    path: '{{slug}}/+page'
    create: true
    media_folder: /uploads
    fields:
      - name: title
        label: Titre
      - name: body
        label: Description
        widget: markdown
      - name: models
        label: Modèles
        widget: list
        fields:
          - name: title
            label: Titre
          - name: cover
            label: Image
            widget: image
          - name: description
            label: Description
            widget: markdown