backend:
  name: git-gateway
  branch: master
local_backend: true
locale: fr
media_folder: /static/uploads
public_folder: /uploads
site_url: https://claire-olives-design.netlify.app
display_url: https://claire-olives-design.netlify.app
logo_url: https://claire-olives-design.netlify.app/uploads/logo.png
collections:
  - name: pages
    label: Pages
    files:
      - name: featured
        label: À la une
        file: src/routes/featured.md
        fields:
          - name: image
            label: Image
            widget: image
            required: false
          - name: video
            label: Vidéo
            required: false
          - name: content
            label: Texte
      - name: carousels
        label: Carrousels
        file: src/routes/carousels.md
        fields:
          - name: carousels
            label: Carrousels
            label_singular: Carrousel
            widget: list
            identifier_field: path
            fields:
              - name: path
                label: Chemin
              - name: models
                label: Modèles
                widget: relation
                collection: objects
                value_field: 'models.*.title'
                search_fields: ['title_singular', 'models.*.title']
                display_fields: ['title_singular', 'models.*.title']
                multiple: true
                min: 3
      - name: about
        label: About
        file: src/routes/about/+page.md
        preview_path: about
        fields:
          - name: title
            label: Titre
          - name: image
            label: Image
            widget: image
          - name: caption
            label: Légende
            required: false
          - name: body
            label: Texte
            widget: markdown
      - name: animations
        label: Animations
        file: src/routes/animations/+page.md
        preview_path: animations
        fields:
          - name: animations
            label: Animations
            widget: list
            fields:
              - name: url
                label: Lien
              - name: title
                label: Titre
              - name: caption
                label: Légende
                required: false
                widget: markdown
      - name: archives
        label: Archives
        file: src/routes/archives/+page.md
        preview_path: archives
        fields:
          - name: archives
            label: Archives
            label_singular: Archive
            widget: list
            identifier_field: caption
            fields:
              - name: image
                label: Image
                widget: image
              - name: caption
                label: Légende
      - name: misc
        label: Vrac
        file: src/routes/vrac/+page.md
        preview_path: vrac
        fields:
          - name: gallery
            label: Images
            label_singular: Image
            widget: list
            fields:
              - name: image
                label: Image
                widget: image
              - name: caption
                label: Légende
                required: false
      - name: events
        label: Events
        file: src/routes/events/+page.md
        preview_path: events
        fields:
          - name: events
            label: Events
            label_singular: Event
            widget: list
            add_to_top: true
            identifier_field: title
            fields:
              - name: date
                label: Date
                widget: datetime
                date_format: DD/MM/YYYY
                time_format: false
              - name: title
                label: Titre
              - name: description
                label: Description
                widget: markdown
              - name: cover
                label: Image principale
                widget: image
              - name: caption
                label: Légende
                required: false
              - name: videos
                label: Vidéos
                label_singular: Vidéo
                widget: list
                required: false
                fields:
                  - name: url
                    label: Lien
                  - name: caption
                    label: Légende
                    required: false
              - name: images
                label: Images
                label_singular: Image
                widget: list
                required: false
                fields:
                  - name: image
                    label: Image
                    widget: image
                  - name: caption
                    label: Légende
                    required: false
  - name: objects
    label: Objets
    label_singular: Objet
    folder: src/routes/objets
    path: '{{slug}}/+page'
    preview_path: 'objets/{{slug}}'
    create: true
    fields:
      - name: title
        label: Titre
      - name: title_singular
        label: Titre (singulier)
      - name: body
        label: Description
        widget: markdown
      - name: models
        label: Modèles
        widget: list
        fields:
          - name: title
            label: Titre
          - name: subtitle
            label: Sous-titre
          - name: cover
            label: Image principale
            widget: image
          - name: zenithal_view
            label: Vue zénithale
            widget: image
            required: false
          - name: lateral_view
            label: Vue latérale
            widget: image
            required: false
          - name: description
            label: Description
            widget: markdown
            required: false
  - name: luminaires
    label: Luminaires
    label_singular: Lampe
    file: src/routes/objets/luminaires/+page.md
    preview_path: objets/luminaires
    fields:
      - name: description
        label: Description générale
        widget: markdown
      - name: body
        label: Description
        widget: markdown
      - name: images
        label: Images
        label_singular: Image
        widget: list
        required: false
        fields:
          - name: image
            label: Image
            widget: image
          - name: caption
            label: Légende
            required: false
      - name: models
        label: Modèles
        widget: list
        fields:
          - name: title
            label: Titre
          - name: dimensions
            label: Dimensions
          - name: lateral_view
            label: Vue latérale
            widget: image
            required: false
          - name: cover
            label: Image
            widget: image
            required: false
          - name: description
            label: Description
            widget: markdown
            required: false
          - name: variants
            label: Variations
            label_singular: Variation
            widget: list
            fields:
              - name: title
                label: Titre
              - name: cover
                label: Image
                widget: image
